language: go
go:
  - 1.4
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/cloud9-tools/gocov-merge
script:
  - ./goveralls.sh
